feat: [PIE-8752]: text area editable component
harness/uicore pull request #1020
Opened 2023-04-07 08:34 UTC by vikrant-harness

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2023-04-15 19:37 UTC, vikrant-harness commented
retrigger typecheck

2023-04-15 19:37 UTC, vikrant-harness commented
retrigger build

2023-04-15 19:37 UTC, vikrant-harness commented
retrigger jest

2023-04-17 17:46 UTC, rameshx requested changes

2023-04-17 17:46 UTC, rameshx commented on packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx
> +              const position = firstHalf.length + 2 + item.length + 2
move the comment at line 185 to the `else` block and add a new comment for this `position`

2023-04-17 17:46 UTC, rameshx commented on packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx
> +              // this is required to maintain the carrot position
🥕
```suggestion
              // this is required to maintain the caret position
```

2023-04-17 17:46 UTC, rameshx commented on packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx
> +              const offset = childNodesTextLength[childIndex - 1] - position + 2
better to add a comment here for more info on `+ 2` and `childIndex - 1`

2023-04-17 17:46 UTC, rameshx commented on packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx
> +    }
this function can be defined outside

2023-04-17 17:46 UTC, rameshx commented on packages/uicore/src/components/TextAreaEditable/TextAreaEditable.css
> +  width: 300px;
Do you think it's better if the width is customizable?

2023-04-17 17:46 UTC, rameshx commented on packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
> +    .flatMap(r => {
Why is `flatMap` needed here?

2023-04-17 17:46 UTC, rameshx commented on packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
> +}
`getCaretIndex` this function is repeated

2023-04-17 17:46 UTC, rameshx commented on packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
> +function setCaret(element: ChildNode, index: any): void {
Will the type of `index` be anything other than `number`?

2023-04-17 17:46 UTC, rameshx commented on packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
> +      })
This is repeated. Can this logic be extracted to a function to reuse?

2023-04-17 18:24 UTC, samarth-sharma31 requested changes

2023-04-18 10:36 UTC, vikrant-harness commented on packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx
> +  newExpressionComponent?: boolean
We are going to remove the old component after a few weeks itself , and the FF name is in sync with the prop name

2023-04-18 12:33 UTC, rameshx commented on packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
> +    .flatMap(r => {
`Array.prototype.map` should work here.

2023-04-18 12:33 UTC, rameshx commented on packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx
> +              }, [])
Use the newly added function (`createChildNodeLengthSumArray`) here too.

2023-04-18 12:54 UTC, vikrant-harness commented on packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
> +    .flatMap(r => {
Any specific reason to not use flatMap

2023-04-18 13:03 UTC, rameshx approved these changes

2023-04-18 13:09 UTC, samarth-sharma31 approved these changes

2023-04-19 05:48 UTC, samarth-sharma31 approved these changes

2023-04-19 05:53 UTC, rameshx approved these changes

2023-04-19 05:57 UTC, merged