fix: [CDS-75410]: suppress onInteraction warning + optimise ExpressionDropdown
harness/uicore pull request #1122
Opened 2023-07-31 17:56 UTC by PratyushGar

- Avoid unnecessary re-renders for Expression Dropdown component
- Fixes `[Blueprint] <Popover> onInteraction is ignored when uncontrolled.` warning from tooltip component 
- Added safe check for `Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.` error when element in setCaret is not of type `Node`

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2023-07-31 19:13 UTC, vikrant-harness approved these changes

2023-07-31 22:19 UTC, rameshx requested changes

2023-07-31 22:19 UTC, rameshx commented on packages/uicore/src/components/ExpressionDropdown/ExpressionDropdown.tsx
> +    // eslint-disable-next-line react/display-name
display name could be useful during debugging

2023-07-31 22:19 UTC, rameshx commented on packages/uicore/src/components/ExpressionDropdown/ExpressionDropdown.tsx
> +  }, [dropDownItemClickHandler, isOpen, setIsOpen])
Let's memoize `dropDownItemClickHandler`

2023-07-31 22:19 UTC, rameshx commented on packages/uicore/src/components/ExpressionDropdown/ExpressionDropdown.tsx
> +  }, [dropDownItemClickHandler, isOpen, setIsOpen])
`dropDownItemClickHandler` changes every time causing `overflowListRenderer` to change

2023-07-31 22:19 UTC, rameshx commented on packages/uicore/src/components/ExpressionDropdown/ExpressionDropdown.tsx
> +  const shallShowNesting = (item: TrieNode) => item.children.some(child => child.children.length !== 0)
This is not added now, but can we rename `shallShowNesting` to `showDropdownIcon` or `hasGrandchildren`?

2023-08-01 03:41 UTC, abhinavrastogi-harness reviewed
Looks good mostly

2023-08-01 06:23 UTC, PratyushGar commented on packages/uicore/src/frameworks/Tooltip/Tooltip.tsx
> -      }}
Yes verified, this works fine. This was an additional conditional added, which is not required as `stopPropagation` function will take care of handling these actions when the span is clicked. 

https://github.com/harness/uicore/assets/100121280/5a5d45ba-c67e-4eb9-919d-3d54aab1eb88

2023-08-01 06:42 UTC, rameshx commented on packages/uicore/src/components/ExpressionDropdown/ExpressionDropdown.tsx
> +  )
Can we check if a functional state update be used for `setQueryValue` to access the previous query and remove `query` from deps?

2023-08-01 06:50 UTC, rameshx approved these changes

2023-08-01 06:54 UTC, vikrant-harness approved these changes

2023-08-01 07:02 UTC, merged