feat: [CDS-78994]: Update KVTagInput to show create tag popover
harness/uicore pull request #1177
Opened 2023-10-17 20:41 UTC by rameshx

This updates the KVTagInput to render a popover containing the `Create ${tag}` menu item. This improves the UX by letting the users know a tag is created only after pressing enter or clicking the `Create ${tag}` item.

https://github.com/harness/uicore/assets/52284933/8be47918-a0c9-4d47-9b42-d46ae70d29d5

2023-10-17 20:56 UTC, sahithikolichala submitted a review, later dismissed

2023-10-17 21:06 UTC, rameshx commented on yarn.lock
This is generated after running `npm_config_yes=true npx yarn-audit-fix`. Getting this error without these changes:

```
10% building 0/1 entries 0/0 dependencies 0/0 modulesnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/Users/rameshreddy/Documents/uicore/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/Users/rameshreddy/Documents/uicore/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/Users/rameshreddy/Documents/uicore/node_modules/@storybook/builder-webpack5/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/Users/rameshreddy/Documents/uicore/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:868:17)
    at handleParseResult (/Users/rameshreddy/Documents/uicore/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:934:10)
    at /Users/rameshreddy/Documents/uicore/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:1026:4
    at processResult (/Users/rameshreddy/Documents/uicore/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:743:11)
    at /Users/rameshreddy/Documents/uicore/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:807:5
    at /Users/rameshreddy/Documents/uicore/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/rameshreddy/Documents/uicore/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at /Users/rameshreddy/Documents/uicore/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Command failed with exit code 1.
```

2023-10-17 21:06 UTC, rameshx commented on packages/uicore/src/components/FormikForm/FormikForm.tsx
> +  const { separator = /[,\n\r]/ } = tagsProps ?? {}
`/[,\n\r]/` is the default separator that is used currently

2023-10-18 04:38 UTC, pankajsingh-harness approved these changes

2023-10-18 18:06 UTC, sahithikolichala approved these changes

2023-10-18 22:44 UTC, abhinavrastogi-harness requested changes

2023-10-18 22:44 UTC, abhinavrastogi-harness commented on yarn.lock
why do we have a change in the lockfile? seems unrelated.
looks like some new dependencies also got added.

2023-10-19 05:06 UTC, abhinavrastogi-harness approved these changes

2023-10-19 05:29 UTC, rameshx commented on yarn.lock
This error is thrown when using the latest version of node 16, 16.20.2. Keeping this change as it is needed for everyone using the latest v16. Ran all unit tests in uicore and harness-core-ui to ensure this change is not breaking anything.

2023-10-19 05:31 UTC, pankajsingh-harness approved these changes

2023-10-19 05:38 UTC, merged