feat: [CDS-93035]:k8s-patch-icon
harness/uicore pull request #1263
Opened 2024-03-21 15:16 UTC by litvinovstas

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2024-03-21 15:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/uicore?pullRequest=1263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/uicore?pullRequest=1263) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/uicore?pullRequest=1263) it.</sub>

2024-03-21 15:22 UTC, bot2-harness commented
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2382

2024-03-25 11:23 UTC, shivanand-harness requested changes

2024-03-25 11:23 UTC, shivanand-harness commented on packages/icons/src/k8s-patch.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="none" xmlns:v="https://vecta.io/nano"><g stroke="#0278d5"><path d="M15.312 12.021c2.305 2.305 6.043 2.305 8.348 0 1.375-1.375 1.93
remove fixed height and width and use viewBox instead

2024-03-25 11:34 UTC, bot2-harness commented
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2388

2024-03-25 11:49 UTC, shivanand-harness approved these changes

2024-03-25 13:41 UTC, srdjan-harness approved these changes

2024-03-25 13:54 UTC, merged