chore: [CDS-99648]: Add providers icon for oauth for on-prem
harness/uicore pull request #1393
Opened 2024-09-10 18:02 UTC by sonaligoyal-harness

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2024-09-10 18:10 UTC, bot2-harness commented
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2649

2024-09-11 06:40 UTC, shivanand-harness requested changes

2024-09-11 06:40 UTC, shivanand-harness commented on packages/icons/src/providers.svg
remove height and width properties and check if we can compress the svg image size using this https://vecta.io/nano

2024-09-11 06:42 UTC, sonaligoyal-harness commented on packages/icons/src/providers.svg
I compressed it using yarn svgo, will check using the above one

2024-09-11 07:23 UTC, bot2-harness commented
Image snapshots failed please check https://console.cloud.google.com/storage/browser/ui-team-bucket/uicore-2651

2024-09-12 11:16 UTC, closed without merging