fix: [CDS-34662]: added prop to the multitypeinput to customize menu
harness/uicore pull request #610
Opened 2022-03-07 23:27 UTC by sahithikolichala

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2022-03-07 23:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/uicore?pullRequest=610) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/uicore?pullRequest=610) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/uicore?pullRequest=610) it.</sub>

2022-03-07 23:33 UTC, cjlee01 approved these changes

2022-03-08 04:07 UTC, kapilkumawat86 requested changes

2022-03-08 04:07 UTC, kapilkumawat86 commented on src/components/MultiTypeInput/MultiTypeInput.tsx
> +  showMultiTypeInputMenu?: boolean
Instead of using the boolean prop lets use, if we get allowed type is Fixed, then just don't show the menu at all

2022-03-08 04:53 UTC, kapilkumawat86 requested changes

2022-03-08 04:53 UTC, kapilkumawat86 commented on src/components/MultiTypeInput/MultiTypeInput.tsx
> +      {defaultAllowedType !== MultiTypeInputType.FIXED ? (
no don't add new props, just check if allowedTypes === ['MultiTypeInputType.FIXED'] then do this

2022-03-08 05:22 UTC, kapilkumawat86 approved these changes
I hope we have tested all the use cases

2022-03-08 17:06 UTC, cjlee01 approved these changes

2022-03-08 17:07 UTC, sahithikolichala commented
retrigger typecheck

2022-03-09 19:13 UTC, merged