fix: [PL-21050]: increase + icon on avatar groups
harness/uicore pull request #635
Opened 2022-03-29 12:26 UTC by swarajcheguri-harness

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2022-03-29 12:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/uicore?pullRequest=635) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/uicore?pullRequest=635) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/uicore?pullRequest=635) it.</sub>

2022-03-29 13:15 UTC, avinashmadhwani02 commented on src/components/Avatar/Avatar.tsx
> +  plusIconFontSize: string
why are we taking this from props?

2022-03-29 13:16 UTC, avinashmadhwani02 requested changes

2022-03-29 13:23 UTC, swarajcheguri-harness commented on src/components/Avatar/Avatar.tsx
> +  plusIconLineHeight: string
in order make + icon to be kind of center aligned. Other ways to achieve this are appreciated

2022-03-29 13:24 UTC, swarajcheguri-harness commented on src/components/Avatar/Avatar.tsx
> +    plusIconFontSize: '14px',
want to keep the icon size open for change and not relative  to anything

2022-03-29 13:46 UTC, avinashmadhwani02 commented on src/components/Avatar/Avatar.tsx
> +    contentStyle.lineHeight = sizes[size].plusIconLineHeight
if we are anyways mutating contentStyle, why do we need `updatedContentStyle`?

2022-03-30 10:07 UTC, avinashmadhwani02 approved these changes

2022-03-30 10:18 UTC, abhinavrastogi-harness approved these changes

2022-04-05 11:19 UTC, merged