fix: [CDS-38229]: added createpr icon
harness/uicore pull request #696
Opened 2022-06-06 21:54 UTC by sahithikolichala

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2022-06-06 21:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/uicore?pullRequest=696) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/uicore?pullRequest=696) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/uicore?pullRequest=696) it.</sub>

2022-06-06 21:56 UTC, cjlee01 approved these changes

2022-06-06 22:03 UTC, tan-nhu submitted a review, later dismissed

2022-06-06 22:36 UTC, abhinavrastogi-harness requested changes

2022-06-06 22:36 UTC, abhinavrastogi-harness commented on packages/icons/src/create-pr.svg
> +<svg width="26" height="23" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.786 1.95c-.513 0-.929.428-.929.956v17.223c0 .529.416.957.929.957h20.428c
pls remove height/width and use viewbox instead. pls replace hex fill color with `currentColor`.
 
 see SVG guidelines here: https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/1963262066/SVG+Guidelines+Best+Practices

2022-06-07 09:27 UTC, sahithikolichala commented
@abhinavrastogi-harness  this image is copied from figma as svg

2022-06-07 11:40 UTC, sahithikolichala commented
@abhinavrastogi-harness  updated with designer suggested icon

2022-06-07 16:07 UTC, abhinavrastogi-harness commented on packages/icons/src/create-pr.svg
> +<svg viewBox="0 0 32 33" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M5.786 6.449c-.513 0-.929.428-.929.957v17.223c0 .529.416.957.929.957h20.428c.5
please use `currentColor` for fill

2022-06-07 18:29 UTC, closed without merging