feat: [CCM-8226]: Inventory Dashboard icons
harness/uicore pull request #769
Opened 2022-07-25 05:06 UTC by jyotiarora-harness

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2022-07-25 07:00 UTC, abhinavrastogi-harness requested changes

2022-07-25 07:00 UTC, abhinavrastogi-harness commented on packages/icons/src/azure-vm.svg
> +<image id="image0_494_4911" width="300" height="300" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAMbWlDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAhGQEnoTRHqREkKLICAd
Same. This is png

2022-07-26 03:34 UTC, abhinavrastogi-harness submitted a review, later dismissed

2022-07-26 09:59 UTC, abhinavrastogi-harness approved these changes

2022-07-26 10:21 UTC, jenil-harness approved these changes

2022-07-26 10:22 UTC, merged