feat: [CCM-9557]: Add CCM Connector Icons
harness/uicore pull request #854
Opened 2022-10-20 15:15 UTC by rajarshee-harness

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2022-10-27 04:48 UTC, jenil-harness requested changes

2022-10-27 04:48 UTC, jenil-harness commented on packages/icons/package.json
> +  "version": "1.70.1",
```suggestion
  "version": "1.71.0",
```

2022-10-27 04:48 UTC, jenil-harness commented on packages/icons/package.json
> +  "version": "1.70.1",
Should be a minor version change

2022-10-28 07:04 UTC, jenil-harness approved these changes

2022-10-28 07:16 UTC, rishik30 approved these changes

2022-10-28 07:17 UTC, merged