fix: [SCM-46]: added new icons
harness/uicore pull request #913
Opened 2022-12-05 23:27 UTC by sahithikolichala

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2022-12-05 23:54 UTC, tan-nhu requested changes

2022-12-05 23:54 UTC, tan-nhu commented on packages/icons/src/pull-request.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Remove height and width

2022-12-05 23:54 UTC, tan-nhu commented on packages/icons/src/solid-error.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
Remove height and width

2022-12-06 00:07 UTC, tan-nhu approved these changes

2022-12-06 00:13 UTC, cjlee01 approved these changes

2022-12-06 00:29 UTC, merged