feat: [CDS-53210]: Show fixed component if type is expression for mul…
harness/uicore pull request #985
Opened 2023-02-21 07:20 UTC by sonaligoyal-harness

…titypeinput text area

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- StyleLint: `retrigger stylelint`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- ImageSnapshot `retrigger ImageSnapshot`

2023-02-22 06:25 UTC, rameshx submitted a review, later dismissed

2023-02-22 08:00 UTC, rameshx approved these changes

2023-02-22 08:31 UTC, AshwinBhatkal-Harness requested changes
We should not be doing this. This is a very generic change. Will affect a lot of places. We do not need it everywhere.

Instead add a prop to handle it. The prop should take care of allowing the text field to expand when it is expression.

2023-02-23 11:59 UTC, AshwinBhatkal-Harness approved these changes

2023-02-23 12:04 UTC, merged